/**
 * deployScriptGen.ts
 * Utility: Generate a deploy.js script with dynamic constructor arguments.
 *
 * In Phase 3, the deploy.js template already exists in the Docker image at /app/scripts/deploy.js.
 * This utility is used in Phase 4 to generate a PROJECT-SPECIFIC deploy script that:
 *   1. Knows the exact contract name
 *   2. Has constructor args embedded (or reads from constructor-args.json)
 *   3. Outputs result.json to the shared volume
 *
 * The generated script is placed at: sandboxPath/scripts/deploy.js
 */

export interface DeployScriptOptions {
  contractName: string;
  constructorArgs?: unknown[];
  /**
   * If true, the contract uses payable constructor and value should be passed.
   * value is in wei string format.
   */
  payableValue?: string;
}

/**
 * Generate a deploy script string for the given contract.
 *
 * The script:
 * 1. Imports hardhat ethers
 * 2. Deploys the named contract with constructor args
 * 3. Writes ABI + bytecode + address to /app/project/result.json
 */
export function generateDeployScript(options: DeployScriptOptions): string {
  const { contractName, constructorArgs = [], payableValue } = options;

  // Serialize constructor args to JS literal
  const argsLiteral = JSON.stringify(constructorArgs);
  const overridesLiteral = payableValue
    ? `, { value: ethers.parseUnits("${payableValue}", "wei") }`
    : '';

  return `
/**
 * Auto-generated deploy script for: ${contractName}
 * Generated by SContract Backend — DO NOT EDIT
 * Generated at: ${new Date().toISOString()}
 */
const { ethers, artifacts } = require("hardhat");
const fs = require("fs");
const path = require("path");

const RESULT_PATH = path.join("/app/project", "result.json");

function writeResult(data) {
  fs.writeFileSync(RESULT_PATH, JSON.stringify(data, null, 2), "utf-8");
  console.log("[deploy] Result written to", RESULT_PATH);
  console.log("RESULT_JSON:" + JSON.stringify(data));
}

async function main() {
  try {
    const constructorArgs = ${argsLiteral};
    console.log("[deploy] Deploying ${contractName} with args:", constructorArgs);

    const [deployer] = await ethers.getSigners();
    console.log("[deploy] Deployer address:", deployer.address);

    const Factory = await ethers.getContractFactory("${contractName}");
    const contract = await Factory.deploy(...constructorArgs${overridesLiteral});
    await contract.waitForDeployment();

    const address = await contract.getAddress();
    const deployTx = contract.deploymentTransaction();
    const receipt = deployTx ? await deployTx.wait() : null;

    const artifact = await artifacts.readArtifact("${contractName}");

    writeResult({
      success: true,
      contractName: "${contractName}",
      address,
      abi: artifact.abi,
      bytecode: artifact.bytecode,
      deployTxHash: deployTx ? deployTx.hash : null,
      blockNumber: receipt ? receipt.blockNumber : null,
      gasUsed: receipt ? receipt.gasUsed.toString() : null,
    });

    console.log("[deploy] ✅ Success! Contract at:", address);
  } catch (err) {
    writeResult({
      success: false,
      contractName: "${contractName}",
      error: err.message || String(err),
      details: err.stack || "",
    });
    console.error("[deploy] ❌ Error:", err.message);
    process.exit(1);
  }
}

main();
`.trimStart();
}

/**
 * Generate a minimal compile-only script.
 * Used in Phase 3 testing to verify compilation without deployment.
 */
export function generateCompileScript(contractName: string): string {
  return `
/**
 * Auto-generated compile-only script for: ${contractName}
 * Generated by SContract Backend
 */
const { artifacts, run } = require("hardhat");
const fs = require("fs");
const path = require("path");

const RESULT_PATH = path.join("/app/project", "result.json");

async function main() {
  try {
    console.log("[compile] Starting compilation...");
    await run("compile");
    console.log("[compile] Compilation complete.");

    const artifact = await artifacts.readArtifact("${contractName}");

    const result = {
      success: true,
      contractName: "${contractName}",
      abi: artifact.abi,
      bytecode: artifact.bytecode,
      deployedBytecode: artifact.deployedBytecode,
    };

    fs.writeFileSync(RESULT_PATH, JSON.stringify(result, null, 2), "utf-8");
    console.log("[compile] ✅ ABI and bytecode written to result.json");
    console.log("RESULT_JSON:" + JSON.stringify(result));
  } catch (err) {
    const result = {
      success: false,
      contractName: "${contractName}",
      error: err.message || String(err),
      details: err.stack || "",
    };
    fs.writeFileSync(RESULT_PATH, JSON.stringify(result, null, 2), "utf-8");
    console.error("[compile] ❌ Error:", err.message);
    process.exit(1);
  }
}

main();
`.trimStart();
}
